<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PageController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\HomePageController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\ShopController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\VisitorController;
use App\Http\Controllers\SuperAdminController;

Route::get('/', [PageController::class, 'index']);
Route::get('/mainPage',[PageController::class,'index']);
Route::get('/login', [LoginController::class, 'index']);
Route::post('/login',[LoginController::class,'check']);
Route::get('/register', [RegisterController::class, 'index']);
Route::post('/register',[RegisterController::class,'store']);
Route::get('/logout',[LogoutController::class,'logout']);
Route::get('/customerHomePage',[HomePageController::class,'index']);
Route::get('/superadminHomePage',[HomePageController::class,'index']);
Route::get('/staffHomePage',[HomePageController::class,'index']);
Route::get('/technicianHomePage',[HomePageController::class,'index']);
Route::get('/shop',[VisitorController::class, 'shop']); 
Route::get('/contactUs', [VisitorController::class, 'contactUs']);
Route::get('/storeLocation',[VisitorController::class, 'storeLocation']); 
Route::get('/product/{id}', [VisitorController::class, 'productDetail'])->name('product.detail');
Route::post('/visitorAddCart', [VisitorController::class, 'redirectlogin'])->name('visitor.add.to.cart');
Route::get('/customer/shop',[CustomerController::class,'shop']);
Route::get('/customer/service',[CustomerController::class,'bookService'])->name('customer.book.service');
Route::post('/customer/service',[CustomerController::class, 'storeService']); 
Route::get('/customer/contactUs', [CustomerController::class, 'contactUs']);
Route::get('/customer/storeLocation', [CustomerController::class, 'storeLocation']);
Route::get('/customer/product/{id}', [CustomerController::class, 'productDetail'])->name('product.detail');
Route::post('/customer/cart/add', [CustomerController::class, 'addToCart']);
Route::get('/customer/cart', [CustomerController::class, 'viewCart']);
Route::post('/customer/cart/update', [CustomerController::class, 'updateCart']);
Route::get('/customer/cart/remove/{id}', [CustomerController::class, 'removeFromCart']);
Route::get('/customer/profile', [CustomerController::class, 'viewProfile']);
Route::post('/customer/profile/update', [CustomerController::class, 'updateProfile']);
Route::get('/customer/order', [CustomerController::class, 'order'])->name('customer.order');
Route::get('/superadmin/staffList', [SuperAdminController::class, 'staffList'])->name('superadmin.staffList');
Route::get('/superadmin/staffList/addStaff', [SuperAdminController::class, 'addStaff'])->name('superadmin.addStaff');