<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PageController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\HomePageController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\ShopController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\VisitorController;
use App\Http\Controllers\SuperAdminController;
use App\Http\Controllers\TechnicianController;

Route::get('/', [PageController::class, 'index']);
Route::get('/mainPage',[PageController::class,'index']);
Route::get('/login', [LoginController::class, 'index']);
Route::post('/login',[LoginController::class,'check']);
Route::get('/register', [RegisterController::class, 'index']);
Route::post('/register',[RegisterController::class,'store']);
Route::get('/logout',[LogoutController::class,'logout']);
Route::get('/customerHomePage',[HomePageController::class,'index']);
Route::get('/superadminHomePage',[HomePageController::class,'index']);
Route::get('/staffHomePage',[HomePageController::class,'index']);
Route::get('/technicianHomePage',[HomePageController::class,'index']);
Route::get('/shop',[VisitorController::class, 'shop']); 
Route::get('/contactUs', [VisitorController::class, 'contactUs']);
Route::get('/storeLocation',[VisitorController::class, 'storeLocation']); 
Route::get('/product/{id}', [VisitorController::class, 'productDetail'])->name('product.detail');
Route::post('/visitorAddCart', [VisitorController::class, 'redirectlogin'])->name('visitor.add.to.cart');
Route::get('/customer/shop',[CustomerController::class,'shop']);
Route::get('/customer/service',[CustomerController::class,'bookService'])->name('customer.book.service');
Route::post('/customer/service',[CustomerController::class, 'storeService']); 
Route::get('/customer/contactUs', [CustomerController::class, 'contactUs']);
Route::get('/customer/storeLocation', [CustomerController::class, 'storeLocation']);
Route::get('/customer/product/{id}', [CustomerController::class, 'productDetail'])->name('product.detail');
Route::post('/customer/cart/add', [CustomerController::class, 'addToCart']);
Route::get('/customer/cart', [CustomerController::class, 'viewCart']);
Route::post('/customer/cart/update', [CustomerController::class, 'updateCart']);
Route::get('/customer/cart/remove/{id}', [CustomerController::class, 'removeFromCart']);
Route::post('/customer/checkout', [CustomerController::class, 'checkout']);
Route::post('/customer/placeOrder', [CustomerController::class, 'placeOrder']);
Route::get('/customer/profile', [CustomerController::class, 'viewProfile']);
Route::post('/customer/profile/update', [CustomerController::class, 'updateProfile']);
Route::get('/customer/order', [CustomerController::class, 'order'])->name('customer.order');
Route::post('/customer/order/updateOrderStatus', [CustomerController::class, 'updateOrderStatus'])->name('customer.updateOrderStatus');
Route::get('/superadmin/staffList', [SuperAdminController::class, 'staffList'])->name('superadmin.staffList');
Route::get('/superadmin/staffList/addStaff', [SuperAdminController::class, 'addStaff'])->name('superadmin.addStaff');
Route::post('/superadmin/staffList/store', [SuperAdminController::class, 'storeStaff'])->name('superadmin.storeStaff');
Route::delete('/superadmin/staffList/delete/{id}', [SuperAdminController::class, 'deleteStaff'])->name('superadmin.deleteStaff');
Route::get('/superadmin/productList', [SuperAdminController::class, 'productList'])->name('superadmin.productList');
Route::get('/superadmin/productList/addProduct', [SuperAdminController::class, 'addProduct'])->name('superadmin.addProduct');
Route::post('/superadmin/productList/store', [SuperAdminController::class, 'storeProduct'])->name('superadmin.storeProduct');
Route::delete('/superadmin/productList/delete/{id}', [SuperAdminController::class, 'deleteProduct'])->name('superadmin.deleteProduct');
Route::get('/superadmin/productList/edit/{id}', [SuperAdminController::class, 'editProduct'])->name('superadmin.editProduct');
Route::post('/superadmin/productList/update/{id}', [SuperAdminController::class, 'updateProduct'])->name('superadmin.updateProduct');
Route::get('/superadmin/categoryList', [SuperAdminController::class, 'categoryList'])->name('superadmin.categoryList');
Route::get('/superadmin/categoryList/addCategory', [SuperAdminController::class, 'addCategory'])->name('superadmin.addCategory');
Route::post('/superadmin/categoryList/store', [SuperAdminController::class, 'storeCategory'])->name('superadmin.storeCategory');
Route::delete('/superadmin/categoryList/delete/{id}', [SuperAdminController::class, 'deleteCategory'])->name('superadmin.deleteCategory');
Route::get('/superadmin/categoryList/edit/{id}', [SuperAdminController::class, 'editCategory'])->name('superadmin.editCategory');
Route::post('/superadmin/categoryList/update/{id}', [SuperAdminController::class, 'updateCategory'])->name('superadmin.updateCategory');
Route::delete('/superadmin/categoryList/removeProduct/{id}', [SuperAdminController::class, 'removeProductFromCategory']);
Route::get('/superadmin/pageList', [SuperAdminController::class, 'pageList'])->name('superadmin.pageList');
Route::get('/superadmin/webEditor/{id}', [SuperAdminController::class, 'webEditor'])->name('superadmin.webEditor');
Route::post('/superadmin/webEditor/saveEdit/{id}', [SuperAdminController::class, 'saveEdit'])->name('superadmin.saveEdit');
Route::get('/superadmin/serviceRequestList', [SuperAdminController::class, 'serviceRequestList'])->name('superadmin.serviceRequestList');
Route::post('/superadmin/serviceRequestList/assign/{id}', [SuperAdminController::class, 'assignTechnician']);
Route::get('/superadmin/orderList', [SuperAdminController::class, 'orderList'])->name('superadmin.orderList');
Route::post('/superadmin/orderList/updateOrderStatus/{id}', [SuperAdminController::class, 'updateOrderStatus'])->name('superadmin.updateOrderStatus');
Route::get('/superadmin/pageBuilder/{id}', [SuperAdminController::class, 'webEditor'])->name('superadmin.pageBuilder');
Route::post('/superadmin/page/{pageId}/addSection', [SuperAdminController::class, 'addSection'])->name('superadmin.addSection');
Route::post('/superadmin/section/{sectionId}/update', [SuperAdminController::class, 'updateSection'])->name('superadmin.updateSection');
Route::post('/superadmin/sections/reorder', [SuperAdminController::class, 'reorderSections'])->name('superadmin.reorderSections');
Route::delete('/superadmin/section/{sectionId}/delete', [SuperAdminController::class, 'deleteSection'])->name('superadmin.deleteSection');
Route::get('/superadmin/section/{sectionId}/edit', [SuperAdminController::class, 'getSectionEditor'])->name('superadmin.getSectionEditor');
Route::post('/superadmin/section/{sectionId}/toggle', [SuperAdminController::class, 'toggleSection'])->name('superadmin.toggleSection');
Route::get('/', [SuperAdminController::class, 'visitorHome'])->name('home');
Route::post('/technician/updateStatus/{id}', [TechnicianController::class, 'updateStatus']);
Route::get('/technician/jobHistory', [TechnicianController::class, 'jobHistory']);